### ISSUE TITLE
Wedges not working properly

### ISSUE THREAD

**Issue by MajesticBBQ** [TaskaRaine/Ancient-Tools#62]
On a highly modified playthrough and wedges are not working.
They don't place on stripped logs and make stripped logs unbreakable.
Will try to find more information soon.

**Comment by TaskaRaine** [comment]
No need for more information actually! I just published an update that solves both those issues, I think. There was a compatibility issue between Ancient Tools and Chisel Tools. Ancient Tools wedges were adopting the functionality of Chisel Tools wedges. 

As for the stripped logs being unbreakable, that was simply a silly oversight of mine. They can now be broken by any normal means but will only drop the block if the log hasn't been split. Otherwise, it just breaks.

The update is available here on the ModDB: [Ancient Tools 1.5.1](https://mods.vintagestory.at/ancienttools)

If this doesn't solve both issues, feel free to let me know and I'll look into it. Thanks for the report ^.^

**Comment by MajesticBBQ** [comment]
Thank you very much, Glad to see this fixed quite quickly!
