### ISSUE TITLE
Texture Asset not found -- Broken interpolation/substitution for /wood/ directory calls?

### ISSUE THREAD

**Issue by Diometus** [TaskaRaine/Ancient-Tools#75]
Version of mod being used: AncientTools_V1.5.7.zip

Here is my client-main.txt log file:
https://pastebin.com/0cg8Y3aZ

Problem within log file:
Line 471-473
Line 477-479
Line 529-534
Line 1015-1017
Line 1021-1023
Line 1073-1078

My thoughts:
String interpolation with substitution injected into the string within a function or just strictly a Substitution issue? Makes me wonder how it's calling the directory path and then how the substitution is being used since the path is showing but the substitution is failing. You'd think it would fail for all of the textures though. Notice specifically the /wood/ directory it seems it is affecting? Is each directory being called separately with its own series of code? Surely not because that would add to the bloat unnecessarily if this was occurring I'd think.

**Comment by TaskaRaine** [comment]
Oh. I'm actually dynamically replacing the {type} in a custom renderer with a reference to the appropriate texture. I didn't consider that the game would actually be trying to find the texture on game launch and would throw a warning...silly, I don't know why I thought that lol. I should do something else to avoid future confusion.

Either way, it shouldn't be causing any actual problems. It's intentional, just short-sighted xD

**Comment by TaskaRaine** [comment]
This is solved in the next release by moving all the dynamic content into attributes. Thanks for the report!
